name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
      with: # Configura o segredo como uma entrada
        dotnet-version: 2.2.108
      env: # Ou como uma variável de ambiente
        BIPBOP_APIKEY: ${{ secrets.BIPBOP_APIKEY }}
      uses: actions/setup-dotnet@v1
      with:
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
      
